import { Header } from '@/shared/components'
import { inter } from '@/shared/fonts'
import type { Metadata } from 'next'
import './globals.css'

// TODO: Добавить CEO Для страниц
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.variable} antialiased`}>
				<Header />
				{children}
			</body>
		</html>
	)
}
